---
version: '3.9'

services:
  db:
    image: lscr.io/linuxserver/mariadb:latest
    secrets:
      - mariavwdn_root
      - mariavwdn_sql
    environment:
      - MYSQL_ROOT_PASSWORD=/run/secrets/mariavwdn_root
      - MYSQL_PASSWORD=/run/secrets/mariavwdn_sql
      - MYSQL_DATABASE=vaultwarden
      - MYSQL_USER=vaultwarden
      - PUID=15002
      - PGID=15000
      - TZ=America/Boise
    volumes:
      - /nfs/mariadbvtwn/config:/config

  app:
    image: vaultwarden/server:latest
    links:
      - db
    secrets:
      - vaultwardendb_url
      - vaultwarden_domain
      - smtp_username
      - smtp_password
    environment:
      - DATABASE_URL_FILE=/run/secrets/vaultwardendb_url
      - PUID=15001
      - PGID=15000
      - TZ=America/Boise
      - DOMAIN_FILE=/run/secrets/vaultwarden_domain
      - SMTP_HOST=smtp.gmail.com
      - SMTP_FROM_FILE=/run/secrets/smtp_username
      - SMTP_PORT=587
      - SMTP_SECURITY=starttls
      - SMTP_USERNAME_FILE=/run/secrets/smtp_username
      - SMTP_PASSWORD_FILE=/run/secrets/smtp_password
    volumes:
      - /nfs/vaultwarden/data:/data
      - /nfs/vaultwarden/config:/config
    ports:
      - 10035:80

volumes:
  vaultwarden:
  db:

secrets:
  mariavwdn_root:
     external: true
  mariavwdn_sql:
     external: true
  vaultwardendb_url:
     external: true
  smtp_username:
     external: true
  smtp_password:
     external: true
  vaultwarden_domain:
     external: true
