---
version: '3.9'

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=13001
      - PGID=13000
      - UMASK=002
      - TZ=America/Boise
      - DOCKER_MODS=linuxserver/mods:radarr-striptracks
    volumes:
      - /arr:/data
      - sonarr:/config
    ports:
      - 8989:8989

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=13002
      - PGID=13000
      - UMASK=002
      - TZ=America/Boise
      - DOCKER_MODS=linuxserver/mods:radarr-striptracks
    volumes:
      - /arr:/data
      - radarr:/config
    ports:
      - 7878:7878

  # lidarr:
  #   image: lscr.io/linuxserver/lidarr:latest
  #   container_name: lidarr
  #   environment:
  #     - PUID=13003
  #     - PGID=13000
  #     - UMASK=002
  #     - TZ=America/Boise
  #     - DOCKER-MODS=linuxserver/mods:lidarr-flac2mp3
  #   volumes:
  #     - /arr:/data
  #     - lidarr:/config
  #   ports:
  #     - 8686:8686
  #   restart: unless-stopped

  # readarr:
  #   image: lscr.io/linuxserver/readarr:develop
  #   environment:
  #     - PUID=13004
  #     - PGID=13000
  #     - UMASK=002
  #     - TZ=America/Boise
  #   volumes:
  #     - /arr:/data
  #     - readarr:/config
  #   ports:
  #     - 8787:8787
  
  overseerr:
    image: lscr.io/linuxserver/overseerr:develop
    environment:
      - PUID=13005
      - PGID=13000
      - TZ=America/Boise
    volumes:
      - /nfs/overseerr/config:/config
    ports:
      - 5055:5055

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      - PUID=13007
      - PGID=13000
      - UMASK=002
      - TZ=America/Boise
      - WEBUI_PORT=20909
    volumes:
      - /nfs/qbittorrent/config:/config
      - /arr/torrents:/data/torrents
    ports:
      - 20909:20909
      - 6881:6881
      - 6881:6881/udp

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    environment:
      - PUID=13009
      - PGID=13000
      - UMASK=002
      - TZ=America/Boise
    volumes:
      - /nfs/sabnzbd/config:/config
      - /arr/usenet:/data/usenet
    ports:
      - 10027:8080

volumes:
  radarr:
  sonarr:
  readarr:
  lidarr:
