---
version: '3.8'

services:
  db:
    image: mongo:latest
    secrets:
      - mongospotify_root
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongospotify_root
      - PUID=16002
      - PGID=16000
      - TZ=Europe/London
    volumes:
      - mongodb_spotify:/data/db
      - mongoconfig_spotify:/data/configdb

  app:
    image: lscr.io/linuxserver/your_spotify:latest
    links:
      - db
    secrets:
      - your_spotify_public
      - your_spotify_secret
    environment:
      - APP_URL=http://192.168.2.18:10040
      - PUID=16001
      - PGID=16000
      - TZ=Europe/London
      - SPOTIFY_PUBLIC=/run/secrets/your_spotify_public
      - SPOTIFY_SECRET=/run/secrets/your_spotify_secret
      - CORS=all
      - MONGO_ENDPOINT=mongodb://db:27017/your_spotify
    ports:
      - 10040:80
      - 10041:443

volumes:
  your_spotify:
  db:
  mongodb_spotify:
  mongoconfig_spotify:

secrets:
  your_spotify_public:
     external: true
  your_spotify_secret:
     external: true
  mongospotify_root:
     external: true
