---
version: '3.9'

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    environment:
      - PUID=11001
      - PGID=11000
      - TZ=America/Boise
    volumes:
      - /nfs/heimdall/config:/config
    ports:
      - 10014:80
      - 10015:443
