---
version: "3.8"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    environment:
      - PUID=11001
      - PGID=11000
      - TZ=Europe/London
    volumes:
      - /nfs/heimdall/config:/config
    ports:
      - 10014:80
      - 10015:443
