---
version: '3.9'

services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    secrets:
      - frigate_rstp
    environment:
      - PUID=17001
      - GUID=17000
      - TZ=America/Boise
      - FRIGATE_RTSP_PASSWORD=/run/secrets/frigate_rstp
#    privileged: true # this may not be necessary for all setups
    shm_size: "900mb" # update for your cameras based on calculation above
    devices:
#      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
#      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
#      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
#      - /etc/localtime:/etc/localtime:ro
      - /path/to/your/config:/config
      - /path/to/your/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - 8971:8971
      # - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - 8554:8554 # RTSP feeds
      - 8555:8555/tcp # WebRTC over tcp
      - 8555:8555/udp # WebRTC over udp

secrets:
  frigate_rstp:
     external: true
